In [4]:
import Credentials      # Get API keys, etc.
import pandas as pd
from pprint import pprint as pp

apikey = Credentials.apikey
baseurl = 'https://api-na.hosted.exlibrisgroup.com'
queryUpdateItem = '/almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items/{item_pid}?apikey={apikey}'

In [22]:
### Get MMS/Holding/Item IDs, Descriptions, Locations from spreadsheet ###
df = pd.read_csv("FullItemList.csv", converters={'Item ID':str, 'Holdings ID':str, 'MMS ID':str, })

In [23]:
# Strip it down to just the necessary columns
df = df[['MMS ID', 'Holdings ID', 'Item ID', 'Description', 'Permanent Location']]

# Strip leading/trailing space from Description
df.Description = df.Description.str.strip()
# Collapse multiple spaces within the Description
df.Description.replace(' +', ' ', regex=True, inplace=True)

In [26]:
# Add the fields to be filled
df[['EnumA', 'EnumB', 'ChronI', 'ChronJ']] = None
# Create a dataframe to hold JUST records that get filled
filled = pd.DataFrame()

In [27]:
df

,MMS ID,Holdings ID,Item ID,Description,Permanent Location,EnumA,EnumB,ChronI,ChronJ
0,991003093289706388,2276563440006388,23128946300006388,87/40,2L Gov Docs,None,None,None,None
1,991003093289706388,2276563440006388,23128946290006388,87/39,2L Gov Docs,None,None,None,None
2,991003093289706388,2276563440006388,23128946280006388,87/38,2L Gov Docs,None,None,None,None
3,991003093289706388,2276563440006388,23128946270006388,87/37,2L Gov Docs,None,None,None,None
4,991003093289706388,2276563440006388,23128946260006388,87/36,2L Gov Docs,None,None,None,None
...,...,...,...,...,...,...,...,...,...
99995,991003010709706388,2264534640006388,2364534610006388,v.3,LL Curriculum Coll,None,None,None,None
99996,991002691069706388,2264534410006388,2364534400006388,v.1,2L Stacks,None,None,None,None
99997,991002691069706388,2264534410006388,2364534390006388,v.2,2L Stacks,None,None,None,None
99998,991001149919706388,2264533650006388,2364533640006388,v.1-2,LL Curriculum Meeting Room,None,None,None,None
99999,991001149919706388,2264533650006388,2364533630006388,v.3-v.4 p.227,LL Curriculum Meeting Room,None,None,None,None